### ISSUE TITLE
Support monorepo

### ISSUE THREAD

**Issue by vlechemin** [zxch3n/vitest-explorer#6]
Great extension! Is it possible to support a monorepo without `vitest.config.ts` in the root folder?
Thanks!

**Comment by zxch3n** [comment]
Yes. I'll add a plugin config.

**Comment by zxch3n** [comment]
Fixed in v0.1.14

**Comment by vlechemin** [comment]
Could you support using the closest `vitest.config.ts` to the test, and not the one from the root folder?
For now it doesnt support `globals: true` without a root config.
